AWSTemplateFormatVersion: '2010-09-09'
Description: Simple EC2 Instance

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0b32d400456908bf9  # Replace with your region's latest Amazon Linux 2 AMI
      KeyName: aws-key       # Replace with your EC2 key pair
      SecurityGroups:
        - default

Outputs:
  InstanceId:
    Description: Instance ID
    Value: !Ref EC2Instance
