AWSTemplateFormatVersion: '2010-09-09'
Description: Simple EC2 Instance

Resources:
  MyVPC: 
    Type: AWS::EC2::VPC 
    Properties: 
      CidrBlock: 10.0.0.0/24
      EnableDnsSupport: false 
      EnableDnsHostnames: false 
      InstanceTenancy: default
  MySubnet: 
    Type: AWS::EC2::Subnet 
    Properties: 
      CidrBlock: 10.0.0.34/27 
      VpcId: 
        Ref: MyVPC
  Mappings:
    AWSRegionToAMI:
      ap-south-1:
        "64": ami-0b32d400456908bf9
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: 
        Fn::FindInMap: 
          - AWSRegionToAMI 
          - Ref: AWS::Region 
          - "64" 
      SecurityGroupIds: 
        - Fn::GetAtt: 
            - MyVPC 
            - DefaultSecurityGroup 
      SubnetId: 
        Ref: MySubnet

Outputs:
  InstanceId:
    Description: Instance ID
    Value: !Ref MyInstance
