AWSTemplateFormatVersion: '2010-09-09'
Description: Simple EC2 Instance

Resources:
  MyVPC: 
    Type: AWS::EC2::VPC 
    Properties: 
      CidrBlock: 
        Ref: MyVPCCIDRRange 
      EnableDnsSupport: false 
      EnableDnsHostnames: false 
      InstanceTenancy: default
  MySubnet: 
    Type: AWS::EC2::Subnet 
    Properties: 
    CidrBlock: 
      Ref: MyVPCCIDRRange 
    VpcId: 
      Ref: MyVPC
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0b32d400456908bf9  # Replace with your region's latest Amazon Linux 2 AMI
      KeyName: mymumbai-key     # Replace with your EC2 key pair
      SecurityGroups:
        - default
        
Outputs:
  InstanceId:
    Description: Instance ID
    Value: !Ref EC2Instance
